version: '3.1'

services:
  online_gradebook_db:
    container_name: "online_gradebook_db"
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: 30752
      POSTGRES_DB: 2019_gebica_rafal
    volumes:
      - /var/lib/online_gradebook_db-local/postgres:/var/lib/postgresql/data
